name: Publish Python distribution to PyPI

on:
    push:
        tags:
            - "v*" # Trigger on push of version tags (e.g., v0.1.0)

jobs:
    build-n-publish:
        name: Build and publish to PyPI
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine
                  pip install .[dev]  # Install the package and dev dependencies

            - name: Run tests
              run: |
                  pytest tests/  # Run pytest on your tests directory

            - name: Build package
              run: python -m build

            - name: Publish to PyPI
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: twine upload dist/*
