name: Publish Python distribution to PyPI

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version to publish (e.g., v1.2.3)"
                required: true

jobs:
    build-n-publish:
        name: Build and publish to PyPI
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Check if version tag exists
              run: |
                  if ! git rev-parse ${{ github.event.inputs.version }} >/dev/null 2>&1; then
                    echo "Error: Tag ${{ github.event.inputs.version }} does not exist"
                    exit 1
                  fi

            - name: Checkout the tagged version
              run: git checkout ${{ github.event.inputs.version }}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine
                  pip install .[dev]

            - name: Start Flask Server
              run: |
                  python tests/app.py &
                  sleep 1

            - name: Run tests
              run: |
                  pytest tests/

            - name: Build package
              run: python -m build

            - name: Publish to PyPI
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: twine upload dist/*
